---
name: TSJ
title: The Secret Jounals
description: 'India''s digital platform for latest news and reports, insightful analyses,
  opinion on politics, policy, governance, economy, education, defence and culture.

'
tags:
- India
- China
- Pakistan
- BJP
- Tech
- Politics
email: Gmail@iefan.tech
disqus_username: disqus_username
show_hero: true
menu:
- title: Home
  url: "/"
- title: About
  url: "/about"
- title: Contact
  url: "/contact"
- title: Security and Privacy
  url: "/security-and-privacy"
github_username: github_username
facebook_username: https://www.facebook.com/TheSecretJournals
twitter_username: https://twitter.com/TheOfficial_TSJ
instagram_username: https://www.instagram.com/ali_iefan/
linkedin_username: "#"
medium_username: "#"
show_time_bar: true
show_modal_on_exit: false
show_modal_on_finish_post: true
two_columns_layout: true
baseurl: https://www.thesecretjournals.world
url: ''
google_analytics: UA-169224196-1
language: en
categories_folder: category
sent_message_url: "/contact/message-sent/"
markdown: kramdown
highlighter: rouge
permalink: "/:title/"
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: true
use_logo: false
paginate_content:
  enabled: true
  debug: false
  collections:
  - posts
  - history
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true
sass:
  style: compressed
plugins:
- jekyll-paginate
- jekyll-paginate-content
- jekyll-youtube
exclude:
- package.json
- package-lock.json
- src
- node_modules
- initpost.sh
- Gemfile
- Gemfile.lock
- gulpfile.js
- README.md
version: ''
